### ISSUE TITLE
The host info is not documented

### ISSUE THREAD

**Issue by manocodes** [daroczig/AWR.Snowflake#1]
Hello, I want to use your library to connect to Snowflake however my connection string seems to be buggy and I cannot find code on how to specify the host URL correctly. Any help is great. 

   my_db <- dbConnect(AWR.Snowflake::Snowflake(), 
                      user = creds$userName,
                            password = creds$passWord,
                            account_name = creds$account,
                              db = "PRODUCT_DATA_LAKE")

**Comment by daroczig** [comment]
The host URL is based on the `account_name` as per the JDBC driver and works fine in the accounts I've tested so far -- but please check the JDBC driver's connection params that you may use at https://docs.snowflake.net/manuals/user-guide/jdbc-configure.html#connection-parameters

Please reopen if you see any issue with the R wrapper.
